# Generated by Django 5.1.1 on 2024-11-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_rename_class_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(default='', max_length=120)),
                ('room', models.CharField(default='', max_length=10)),
                ('schedule', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
