# Generated by Django 5.1.1 on 2024-11-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_attendance'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hour',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attend', 'Attend'), ('not_attend', 'Did not Attend')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
