# Generated by Django 5.1.1 on 2024-11-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=255)),
                ('qr_url', models.CharField(default='', max_length=255)),
                ('class_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=255)),
                ('question_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.options')),
                ('question_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('student_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_code', 'question_id'), name='unique_host_migration')],
            },
        ),
    ]
