# Generated by Django 5.1.1 on 2024-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(default=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
