# Generated by Django 5.1.1 on 2024-11-26 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Courses',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
